name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  resolve:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Resolve dependencies
        run: swift package resolve
        
  build:
    runs-on: macos-latest
    needs: resolve
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Resolve dependencies
      run: swift package resolve
      
    - name: Build
      run: swift build -v
      
  test:
    runs-on: macos-latest
    needs: resolve
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run tests
        run: swift test -v
      
